dateLibrary: "java8"
useJakartaEe: "true"
returnSuccessCode: "true"
skipDefaultInterface: "true"
useOptional: "false"
interfaceOnly: "true"
openApiNullable: "false"
useTags: "true"
booleanGetterPrefix: "is"
useBeanValidation: "true"
useSpringBoot3: "true"
unhandledException: "true"
